### ISSUE TITLE
[Feature Request] Improve the Terraform Documentation

### ISSUE THREAD

**Issue by cheelim1** [temporalio/terraform-provider-temporalcloud#114]
### Is your feature request related to a problem? Please describe.

Currently in the terraform documentation to explain how to import the user did not describe what are the details needed to import the user.
https://registry.terraform.io/providers/temporalio/temporalcloud/latest/docs/resources/user#import

This `terraform import temporalcloud_user.terraform terraform.badf00d` is very vague. 
Another thing I would assume the `badf00d` is the temporal user id? I can't find the user id form the console and there's no datasource to retrieve the userid. 

### Describe the solution you'd like
To improve the documentation to explain what are the values needed to import and perhaps a datasource for temporal users.

**Comment by jlacefie** [comment]
+1 to this issue. 

Here are the steps to import a user

command `terraform import temporalcloud_user.owner <owner userid>`

The import process requires

- an entry in the terraform.tf file that matches temporalcloud_user.owner
- passing in the id of the user which can be found using tcld user list

One challenge to overcome with this issue is that docs are auto-generated today.

**Comment by jlacefie** [comment]
closed as dup of several other issues
